[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[context.production.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL"
